dotenv: .env

wallets:
  DEPLOYMENT_PRIVATE: ${DEPLOYMENT_PRIVATE}
  OWNER_PRIVATE: ${OWNER_PRIVATE}
  MAINNET_DEPLOYER: ${MAINNET_DEPLOYER}

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
    vyper:
        version: null